### ISSUE TITLE
Rotary counter with MAX7219, help

### ISSUE THREAD

**Issue by m2snd** [csdexter/MAX7219#1]
First, thanks for this library!

For several days i was working in a code to do a rotary counter and display the numbers in 7-segment display with no sucess, until find this great library.

With code that i find in this website for reading rotary encoders http://www.circuitsathome.com/mcu/reading-rotary-encoder-on-arduino and your library, i have been able to display the numbers in a MAX7219 7 segment display. But there's a problem. When the counter reach the number 10, instead of displaying the number 10, show 01 and so on 11, 21, 31... 
http://youtu.be/2Czfiu0ms4w
Display first the units and after tenths. How can solve that?
Thanks

**Comment by m2snd** [comment]
I uploaded your exemple skecth, MAX7219_7segment, I noticed that the count down from 100, is reversed too 99, 89, 79, 69....

**Comment by csdexter** [comment]
Hi and thanks for writing.

I'm happy you find the library useful. Since you say both your code and the included examples show the digits reversed (I cannot access the linked video as it's private), it logically follows the chips are connected to the displays the other way around (i.e. MAX7219 digit 0 to the rightmost display instead of the leftmost one).

If this convention (of mounting the displays in reverse) is used in many pre-made boards (for example by Adafruit etc.), then it's probably worth implementing mirroring in software to work around it.

Hope this helps!

**Comment by m2snd** [comment]
Sorry the video, i change it for public!
So, is not possible reverse the digits with this library at moment, is this correct?

**Comment by JonathanMalott** [comment]
Hey man,

Sorry but I just threw the code up on github to give other people a starting off point, I can’t help you :(

Hope you figure it out,
Jonathan

**Comment by csdexter** [comment]
@m2snd I can try and add that functionality to the library, but it's a very busy week so I make no promises as to the timeliness of that being committed.

**Comment by m2snd** [comment]
@csdexter i would appreciate that, besides the library would be more complete. Take your time :-) Thanks

**Comment by csdexter** [comment]
Implemented in eca5f1aec7fac3a8dcbd39dd284da10bbd182f79, enjoy :-)
